language: python
python:
- 2.7
- 3.4
install:
- pip install .
- pip install -r requirements.txt
- pip install coveralls
# command to run tests
script: coverage run -m unittest discover tests/
after_success:
- pip install coveralls
- coveralls
